example.property: "I AM IN THE DEFAULT"
spring.jpa.database: "MYSQL"
spring.datasource.platform:  "mysql"
spring.jpa.show-sql: "true"
spring.database.driverClassName: "com.mysql.jdbc.Driver"
spring.datasource.url: "jdbc:mysql://localhost:3306/ms_book_db?serverTimezone=UTC"
spring.datasource.username: "root"
spring.datasource.password: "root"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.MySQL5Dialect"
redis.server: "redis"
redis.port: "6379"
signing.key: "345345fsdfsf5345"