server:
   port: 8888
spring:
  profiles:
    active: native
  cloud:
     config:
       server:
           native:
              searchLocations: file:///C:/Dev/Projets/springMSInAction/confsvr/src/main/resources/config/licensingservice
