server:
   port: 8888

spring:
  cloud:
    config:
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/youma85/config-repo
          searchPaths: licensingservice

#spring:
#  profiles:
#    active: native
#  cloud:
#     config:
#       server:
#           native:
#              searchLocations: file:///C:/Dev/Projets/springMSInAction/confsvr/src/main/resources/config/licensingservice
